### ISSUE TITLE
Getting Exec format error: './simple.vert' when trying to compile a shader using compile_shader.py

### ISSUE THREAD

**Issue by v1rtl** [Twinklebear/webgpu-experiments#1]
## The problem

Hello, I'm trying to write my test renderer for WebGPU, and I'm stuck in the process of compiling GLSL to SPIRV.

Something like:

`glslc -mfmt=c shaders/simple.vert -o out/simple.spv` works, but the script in `shaders` folder produces this:

## Stack trace

```
➜ ./compile_shader.py ./simple.vert main main
Traceback (most recent call last):
  File "./compile_shader.py", line 20, in <module>
    subprocess.check_output(args)
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './simple.vert'
```

I'm a noob in WebGL / shader stuff, so I'm not sure where the problem comes from.

## Shader files

- `simple.frag`:

```glsl
#version 450 core

layout(location = 0) in vec4 vcolor;

layout(location = 0) out vec4 color;

void main(void) {
    color = vcolor;
}
```

- `simple.vert`:

```
#version 450 core

layout(location = 0) in vec4 pos;
layout(location = 1) in vec4 color;

layout(location = 0) out vec4 vcolor;

void main(void) {
    vcolor = color;
    gl_Position = pos;
}
```

## Additional context

Also, in [this article](https://www.willusher.io/graphics/2020/06/15/0-to-gltf-triangle), I'm not sure what arguments I should pass to the `glslc` wrapper script.

I'm trying to compile the `simple.vert` and `simple.frag` files

## System info

- OS: Manjaro Linux x64
- `shaderc` version: `2020.0-1`

thanks in advance!

**Comment by Twinklebear** [comment]
Hey @talentlessguy , thanks for opening this issue!

The Python script expects the first argument to be your glslc compiler, since it doesn't do a search to find it automatically. So your command line should be:

```
./compile_shader.py glslc ./simple.vert main
```

The second `main` argument you don't need, since the compiled shader is printed out to the terminal. You could redirect the output to a file, or copy-paste it into your JS somewhere (like I did in the tutorial). The error output from the script is saying it tried to execute `./simple.vert`, but it wasn't an executable

The blog post is a bit unclear on how to run this, I'll update that to show an example command line.

**Comment by v1rtl** [comment]
@Twinklebear ohh thanks for a quick response! Will try it out asap and write back here if I have progress

also yeah, better update in the post with how u run this script, to prevent future confusion

**Comment by Twinklebear** [comment]
I added info on how to run this https://github.com/Twinklebear/Twinklebear.github.io-jekyll/commit/f2353e99cc95ba7270ddb1573c118e35ab93d2d8 but forgot to close this issue then.
